### ISSUE TITLE
mtr ingress created without IngressClasssName

### ISSUE THREAD

**Issue by rbaumgar** [windup/windup-operator#222]
I have installed mtr 1.0.0 on OpenShift 4.12
I get following alert:

```
**IngressWithoutClassName**
This alert fires when there is an Ingress with an unset IngressClassName for longer than one day.
```

This is the crd
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    description: Route for application's http service.
  name: secure-mtr
  namespace: mtr
  ownerReferences:
    - apiVersion: windup.jboss.org/v1
      kind: Windup
      name: mtr
      uid: dcaa888f-6817-405b-84c0-79a661cb7c53
      controller: true
  labels:
    app: mtr
    application: mtr
    created-by: windup-operator
spec:
  tls:
    - {}
  rules:
    - host: secure-mtr-mtr.apps.<default_route>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mtr
                port:
                  number: 8080
```
